config/routes.rb
Rails.application.routes.draw do
  get 'services', to: 'services#index'
  get 'services/web-development', to: 'services#web_development'
  get 'services/ruby-on-rails', to: 'services#ruby_on_rails'
  get 'services/wordpress', to: 'services#wordpress'
  get 'services/mobile-apps', to: 'services#mobile_apps'
  get 'services/react-native', to: 'services#react_native'
  get 'services/firebase', to: 'services#firebase'

  get 'playbook', to: 'playbook#index'
  get 'playbook/startup', to: 'playbook#startup'
  get 'playbook/test-driven-development', to: 'playbook#test_driven_development'
  get 'playbook/weekly-iterations', to: 'playbook#weekly_iterations'
  get 'playbook/build-measure-learn', to: 'playbook#build_measure_learn'
  get 'playbook/communication', to: 'playbook#communication'
  get 'playbook/lean-project-management', to: 'playbook#lean_project_management'
  get 'playbook/pricing', to: 'playbook#pricing'
  get 'work-with-me/index'
  get 'about/index'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'contact', to: 'contact#index'
  post 'contact/send', to: 'contact#send_email'
  get 'resume', to: 'resume#index'
  get 'my-work', to: 'portfolio#index'

  resources :articles do
    resources :comments, only: [:create, :destroy]
  end

  # development only routes
  if Rails.env.development? || Rails.env.test?
    get 'icons', to: 'icons#index'
  end
  

  root 'welcome#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    has_many :article_tags
    has_many :tags, through: :article_tags
    has_many :comments, dependent: :destroy
    
    validates :title, presence: true,
                      length: { minimum: 5 }

    validates :text, presence: true

    rails_admin do
        list do 
            field :title
            field :text
            field :tags
            field :created_at
            field :updated_at
        end  

        configure :article_tags do
            label 'Tags'
        end
    end
end

app/models/article_tag.rb
class ArticleTag < ApplicationRecord
  belongs_to :article
  belongs_to :tag
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article

  validates :name, presence: true
  validates :text, presence: true
  validates :email, presence: true
end

app/models/portfolio_item.rb
class PortfolioItem < ApplicationRecord
    has_many :portfolio_item_tags
    has_many :tags, through: :portfolio_item_tags
end

app/models/portfolio_item_tag.rb
class PortfolioItemTag < ApplicationRecord
  belongs_to :portfolio_item
  belongs_to :tag
end

app/models/tag.rb
class Tag < ApplicationRecord
    has_many :portfolio_item_tags
    has_many :portfolio_items, through: :portfolio_item_tags

    validates :name, presence: true
    validates :key, presence: true
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/icons_controller.rb
class IconsController < ApplicationController
    def index
        @icon_names = [
            'analysis', 'analysis-1', 'approve', 'attach', 'attractive', 'brainstorming', 'broken-link', 'chat', 'chronometer', 'compass', 'competition', 'content', 'design-tool', 'grid',
            'headphones', 'html', 'image', 'layout', 'loading', 'login', 'pantone', 'paper-plane', 'photo-camera', 'piggy-bank', 'pipette', 'pixel', 'placeholder', 'planning', 'promotion', 'pyramid', 'quality',
            'responsive', 'schedule', 'search', 'security', 'settings', 'sitemap', 'startup', 'support', 'tap', 'target', 'targeting', 'task', 'testing',
            'text','timeline','tools','upload','vector','video-player'
        ]
    end
end

app/controllers/playbook_controller.rb
class PlaybookController < ApplicationController
  def index
  end

  def startup
  end

  def test_driven_development
  end

  def weekly_iterations
  end

  def build_measure_learn
  end

  def communication
  end

  def lean_project_management
  end

  def pricing
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
    def linkedin_url
        return "https://www.linkedin.com/in/john-rake"
    end

    def facebook_url
        return "https://www.facebook.com/john.rake.37"
    end

    def my_job_title
        return "Web Developer"
    end

    def my_full_name
        return "John Rake"
    end

    def my_email
        return "john.rake12@gmail.com"
    end

    def my_location
        return "Olathe, KS USA"
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/icons_helper.rb
module IconsHelper
end

app/helpers/playbook_helper.rb
module PlaybookHelper
end

app/helpers/portfolio_helper.rb
module PortfolioHelper
    def get_portfolio_item_tag_css(portfolio_item)
        return portfolio_item.tags.map{ |tag| tag.key }.join(" ")
    end
end

app/helpers/resume_helper.rb
module ResumeHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/work_with_me_helper.rb
module WorkWithMeHelper
end

app/views/playbook/build_measure_learn.html.erb
<% content_for :title, "Build, Measure, Learn" %>
<h1>Build Measure lean</h1>

app/views/playbook/communication.html.erb
<% content_for :title, "Communication" %>
<h1>Communication</h1>

app/views/playbook/index.html.erb
<% content_for :title, "Playbook" %>
<h1>Playbook#index</h1>
<p>Find me in app/views/playbook/index.html.erb</p>

<ul>
    <li><%= link_to 'Startups', playbook_startup_path %>
    <li><%= link_to 'Build, Measure, Learn', playbook_build_measure_learn_path %>
    <li><%= link_to 'Lean Project Management', playbook_lean_project_management_path %>
    <li><%= link_to 'Weekly Iterations', playbook_weekly_iterations_path %>
    <li><%= link_to 'Test Driven Development', playbook_test_driven_development_path %>
    <li><%= link_to 'Communication', playbook_communication_path %>
    <li><%= link_to 'Pricing', playbook_pricing_path %>
</ul>

app/views/playbook/lean_project_management.html.erb
<% content_for :title, "Lean Project Management" %>
<h1>lean Project Management</h1>

app/views/playbook/pricing.html.erb
<% content_for :title, "Pricing" %>
<h1>Pricing</h1>

app/views/playbook/startup.html.erb
<% content_for :title, "Startups" %>
<h1>Startup</h1>

app/views/playbook/test_driven_development.html.erb
<% content_for :title, "Test Driven Development" %>
<h1>Test Driven Development</h1>

app/views/playbook/weekly_iterations.html.erb
<% content_for :title, "Weekly Iterations" %>
<h1>Weekly Iterations</h1>