config/routes.rb
Rails.application.routes.draw do
  get 'services', to: 'services#index'
  get 'services/web-development', to: 'services#web_development'
  get 'services/ruby-on-rails', to: 'services#ruby_on_rails'
  get 'services/wordpress', to: 'services#wordpress'
  get 'services/mobile-apps', to: 'services#mobile_apps'
  get 'services/react-native', to: 'services#react_native'
  get 'services/firebase', to: 'services#firebase'

  get 'playbook', to: 'playbook#index'
  get 'playbook/startup', to: 'playbook#startup'
  get 'playbook/test-driven-development', to: 'playbook#test_driven_development'
  get 'playbook/weekly-iterations', to: 'playbook#weekly_iterations'
  get 'playbook/build-measure-learn', to: 'playbook#build_measure_learn'
  get 'playbook/communication', to: 'playbook#communication'
  get 'playbook/lean-project-management', to: 'playbook#lean_project_management'
  get 'playbook/pricing', to: 'playbook#pricing'
  get 'work-with-me/index'
  get 'about/index'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'contact', to: 'contact#index'
  post 'contact/send', to: 'contact#send_email'
  get 'resume', to: 'resume#index'
  get 'my-work', to: 'portfolio#index'

  resources :articles do
    resources :comments, only: [:create, :destroy]
  end

  # development only routes
  if Rails.env.development? || Rails.env.test?
    get 'icons', to: 'icons#index'
  end
  

  root 'welcome#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    has_many :article_tags
    has_many :tags, through: :article_tags
    has_many :comments, dependent: :destroy
    
    validates :title, presence: true,
                      length: { minimum: 5 }

    validates :text, presence: true

    rails_admin do
        list do 
            field :title
            field :text
            field :tags
            field :created_at
            field :updated_at
        end  

        configure :article_tags do
            label 'Tags'
        end
    end
end

app/models/article_tag.rb
class ArticleTag < ApplicationRecord
  belongs_to :article
  belongs_to :tag
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article

  validates :name, presence: true
  validates :text, presence: true
  validates :email, presence: true
end

app/models/portfolio_item.rb
class PortfolioItem < ApplicationRecord
    has_many :portfolio_item_tags
    has_many :tags, through: :portfolio_item_tags
end

app/models/portfolio_item_tag.rb
class PortfolioItemTag < ApplicationRecord
  belongs_to :portfolio_item
  belongs_to :tag
end

app/models/tag.rb
class Tag < ApplicationRecord
    has_many :portfolio_item_tags
    has_many :portfolio_items, through: :portfolio_item_tags

    validates :name, presence: true
    validates :key, presence: true
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    http_basic_authenticate_with name: "admin", password: "password", except: [:index, :show]
    
    def index
        @articles = Article.all
    end

    def show
        @article = Article.find(params[:id])
    end

    def new
        @article = Article.new
    end

    def edit
        @article = Article.find(params[:id])
    end

    def create
        @article = Article.new(article_params)

        if @article.save
            redirect_to @article
        else 
            render 'new'
        end
    end

    def update
        @article = Article.find(params[:id])

        if @article.update(article_params)
            redirect_to @article
        else
            render 'edit'
        end
    end

    def destroy
        @article = Article.find(params[:id])
        @article.destroy

        redirect_to articles_path
    end

    private
        def article_params
            params.require(:article).permit(:title, :text)
        end
end

app/controllers/icons_controller.rb
class IconsController < ApplicationController
    def index
        @icon_names = [
            'analysis', 'analysis-1', 'approve', 'attach', 'attractive', 'brainstorming', 'broken-link', 'chat', 'chronometer', 'compass', 'competition', 'content', 'design-tool', 'grid',
            'headphones', 'html', 'image', 'layout', 'loading', 'login', 'pantone', 'paper-plane', 'photo-camera', 'piggy-bank', 'pipette', 'pixel', 'placeholder', 'planning', 'promotion', 'pyramid', 'quality',
            'responsive', 'schedule', 'search', 'security', 'settings', 'sitemap', 'startup', 'support', 'tap', 'target', 'targeting', 'task', 'testing',
            'text','timeline','tools','upload','vector','video-player'
        ]
    end
end

app/controllers/resume_controller.rb
class ResumeController < ApplicationController
    def index
    end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
    def linkedin_url
        return "https://www.linkedin.com/in/john-rake"
    end

    def facebook_url
        return "https://www.facebook.com/john.rake.37"
    end

    def my_job_title
        return "Web Developer"
    end

    def my_full_name
        return "John Rake"
    end

    def my_email
        return "john.rake12@gmail.com"
    end

    def my_location
        return "Olathe, KS USA"
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/icons_helper.rb
module IconsHelper
end

app/helpers/playbook_helper.rb
module PlaybookHelper
end

app/helpers/portfolio_helper.rb
module PortfolioHelper
    def get_portfolio_item_tag_css(portfolio_item)
        return portfolio_item.tags.map{ |tag| tag.key }.join(" ")
    end
end

app/helpers/resume_helper.rb
module ResumeHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/work_with_me_helper.rb
module WorkWithMeHelper
end

app/views/articles/_form.html.erb
<% if @article.errors.any? %>
    <div id="error_explanation">
        <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
        </h2>
        <ul>
        <% @article.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
        </ul>
    </div>
<% end %>

<%= form_with model: @article, local: true do |form| %>
    <p>
        <%= form.label :title %><br>
        <%= form.text_field :title %>
    </p>
    <p>
        <%= form.label :text %><br>
        <%= form.text_area :text %>
    </p>
    <p>
        <%= form.submit %>
    </p>
<% end %>

app/views/articles/edit.html.erb
<h1>Edit article</h1>

<%= render 'form' %>
 
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<%= content_for :title, "Articles" %>

<div id="blog">
  <div class="row">
      <section class="blog col-md-12 bottom_30">
          <div class="col-md-12 content-header">
              <div class="section-title top_30 bottom_15"><span></span><h2>Blog Posts</h2></div>
          </div>
          <div id="grid-blog" class="row">
            <% @articles.each do |article| %>
              <div class="cbp-item">
                  <%= link_to article_path(article), class: "blog-box" do %>
                      <div class="blog-img">
                          <img src="images/blogs/blog-6.jpg" alt="">
                      </div>
                      <div class="blog-box-info">
                          <span class="category">General</span> 
                          <h2 class="title">
                            <%= article.title %>
                          </h2>
                          <p class="little-text">
                            <%= article.text %>
                          </p>
                          <span class="date">
                            <%= article.created_at.strftime('%e %b %y') %>
                          </span>
                      </div>
                  <% end %>
              </div>
            <% end %>
      </section>
  </div>
</div>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<div id="blog-post">
    <div class="row">
        <div class="col-md-8 post">
            <div class="blog-image">
                <img src="../images/blogs/blog-1.jpg" alt="">
            </div>
            <div class="post-content">
                <h1 class="blog-title bottom_30 top_30">
                    <%= @article.title %>
                </h1>
                <%= @article.text %>
            </div>
            <div class="post-comment">
                <div class="section-title bottom_30 top_60"><span></span><h2>Post Comments</h2></div>
                <ul>
                    <% @article.comments.each do |comment| %>
                        <li>
                            <%= render comment, comment: comment  %>
                        </li>
                    <% end %>
                </ul>
            </div>
            <%= render 'comments/form' %>
        </div>
        <div class="col-md-4 blog-sidebar">
            <!-- Category List -->
            <div class="category">
                <div class="section-title bottom_15 top_15"><span></span><h3>Categories</h3></div>
                <ul class="category-list">
                    <li><a href="#">Web Design</a><span>11</span></li>
                    <li><a href="#">Development</a><span>12</span></li>
                    <li><a href="#">Photography</a><span>16</span></li>
                    <li><a href="#">Branding</a><span>16</span></li>
                    <li><a href="#">Other</a><span>16</span></li>
                </ul>
            </div>
            <!-- Popular Post -->
            <div class="post-list">
                <div class="section-title bottom_15 top_60"><span></span><h3>Related Posts</h3></div>
                <ul>
                    <!-- a post -->
                    <li>
                        <a href="#">
                            <div class="info">Development <span>Oct 21, 17</span></div>
                            <p class="little-text">How to vertically center a div for all browsers?</p>
                        </a>
                    </li>
                    <!-- a post -->
                    <li>
                        <a href="#">
                            <div class="info">Web Design <span>April 14, 17</span></div>
                            <p class="little-text">How to convert a Sketch design file into a layered Photoshop file</p>
                        </a>
                    </li>
                    <!-- a post -->
                    <li>
                        <a href="#">
                            <div class="info">Web Design <span>Mar 18, 17</span></div>
                            <p class="little-text">The Bookmarkable Photoshop Tutorial for Beginners</p>
                        </a>
                    </li>
                </ul>
            </div>
            <!-- Advertisement -->
            <div class="advertisement">
                <div class="section-title bottom_30 top_60"><span></span><h3>Advertisement</h3></div>

                <img src="../images/image.jpg" alt="">    
            </div>
        </div> 
    </div>
</div>

<%= link_to 'Edit', edit_article_path(@article) %>
<%= link_to 'Back', articles_path %>