config/routes.rb
Rails.application.routes.draw do
  get 'services', to: 'services#index'
  get 'services/web-development', to: 'services#web_development'
  get 'services/ruby-on-rails', to: 'services#ruby_on_rails'
  get 'services/wordpress', to: 'services#wordpress'
  get 'services/mobile-apps', to: 'services#mobile_apps'
  get 'services/react-native', to: 'services#react_native'
  get 'services/firebase', to: 'services#firebase'

  get 'playbook', to: 'playbook#index'
  get 'playbook/startup', to: 'playbook#startup'
  get 'playbook/test-driven-development', to: 'playbook#test_driven_development'
  get 'playbook/weekly-iterations', to: 'playbook#weekly_iterations'
  get 'playbook/build-measure-learn', to: 'playbook#build_measure_learn'
  get 'playbook/communication', to: 'playbook#communication'
  get 'playbook/lean-project-management', to: 'playbook#lean_project_management'
  get 'playbook/pricing', to: 'playbook#pricing'
  get 'work-with-me/index'
  get 'about/index'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'contact', to: 'contact#index'
  post 'contact/send', to: 'contact#send_email'
  get 'resume', to: 'resume#index'
  get 'my-work', to: 'portfolio#index'

  resources :articles do
    resources :comments, only: [:create, :destroy]
  end

  # development only routes
  if Rails.env.development? || Rails.env.test?
    get 'icons', to: 'icons#index'
  end
  

  root 'welcome#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    has_many :article_tags
    has_many :tags, through: :article_tags
    has_many :comments, dependent: :destroy
    
    validates :title, presence: true,
                      length: { minimum: 5 }

    validates :text, presence: true

    rails_admin do
        list do 
            field :title
            field :text
            field :tags
            field :created_at
            field :updated_at
        end  

        configure :article_tags do
            label 'Tags'
        end
    end
end

app/models/article_tag.rb
class ArticleTag < ApplicationRecord
  belongs_to :article
  belongs_to :tag
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article

  validates :name, presence: true
  validates :text, presence: true
  validates :email, presence: true
end

app/models/portfolio_item.rb
class PortfolioItem < ApplicationRecord
    has_many :portfolio_item_tags
    has_many :tags, through: :portfolio_item_tags
end

app/models/portfolio_item_tag.rb
class PortfolioItemTag < ApplicationRecord
  belongs_to :portfolio_item
  belongs_to :tag
end

app/models/tag.rb
class Tag < ApplicationRecord
    has_many :portfolio_item_tags
    has_many :portfolio_items, through: :portfolio_item_tags

    validates :name, presence: true
    validates :key, presence: true
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
    def index
        @message_sent = params[:message_sent]
    end

    def send_email
        ContactMailer.with(
            name: params[:name],
            email: params[:email],
            message: params[:message],
        ).contact_email.deliver_later

        redirect_to action: :index, message_sent: true
    end
end

app/controllers/icons_controller.rb
class IconsController < ApplicationController
    def index
        @icon_names = [
            'analysis', 'analysis-1', 'approve', 'attach', 'attractive', 'brainstorming', 'broken-link', 'chat', 'chronometer', 'compass', 'competition', 'content', 'design-tool', 'grid',
            'headphones', 'html', 'image', 'layout', 'loading', 'login', 'pantone', 'paper-plane', 'photo-camera', 'piggy-bank', 'pipette', 'pixel', 'placeholder', 'planning', 'promotion', 'pyramid', 'quality',
            'responsive', 'schedule', 'search', 'security', 'settings', 'sitemap', 'startup', 'support', 'tap', 'target', 'targeting', 'task', 'testing',
            'text','timeline','tools','upload','vector','video-player'
        ]
    end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
    def linkedin_url
        return "https://www.linkedin.com/in/john-rake"
    end

    def facebook_url
        return "https://www.facebook.com/john.rake.37"
    end

    def my_job_title
        return "Web Developer"
    end

    def my_full_name
        return "John Rake"
    end

    def my_email
        return "john.rake12@gmail.com"
    end

    def my_location
        return "Olathe, KS USA"
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/icons_helper.rb
module IconsHelper
end

app/helpers/playbook_helper.rb
module PlaybookHelper
end

app/helpers/portfolio_helper.rb
module PortfolioHelper
    def get_portfolio_item_tag_css(portfolio_item)
        return portfolio_item.tags.map{ |tag| tag.key }.join(" ")
    end
end

app/helpers/resume_helper.rb
module ResumeHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/work_with_me_helper.rb
module WorkWithMeHelper
end

app/views/contact/_form.html.erb
<%= form_with url: contact_send_path, local: true, class: "site-form" do |form| %>
    <div class="row">
        <div class="col-md-6">
            <%= text_field_tag :name, nil, class: "site-input", placeholder: "Name", required: true %>
        </div>
        <div class="col-md-6">
            <%= email_field_tag :email, nil, class: "site-input", placeholder: "E-mail", required: true %>
        </div>
        <div class="col-md-12">
            <%= text_area_tag :message, nil, class: "site-area", placeholder: "Message", required: true %>
        </div>
        <div class="col-md-12 top_15 bottom_30">
            <%= submit_tag "Submit", class: "site-btn", type: "Submit" %>
        </div>
    </div>
<% end %>

app/views/contact/index.html.erb
<% content_for :title, "Contact" %>

<div id="contact">
    <div class="row">
        <section class="contact-form col-md-6 padding_30 padbot_45">
            <div class="section-title top_15 bottom_30"><span></span><h2>Contact Form</h2></div>

            <% if @message_sent %>
                <div class="alert alert-success" role="alert">
                    <b>Hey, thanks for getting in touch!</b><br/>

                    <p>I'll respond as soon as I can (usually within a day).</p>
                    <p>
                        Email is definitely the best way to reach me, but you're welcome to message me through any of the contact information to the right.
                    </p>
                    <p>
                        <i>Connect with me on <a href="<% linkedin_url %>" target="_blank">LinkedIn</a> as well. It's a great way to stay in touch down the road and share our projects.</i>
                    </p>
                </div>
            <% else %> 
                <%= render "contact/form" %>
            <% end %>
        </section>
        <!-- Contact Informations -->
        <section class="contact-info col-md-6 padding_30 padbot_45">
            <div class="section-title top_15 bottom_30"><span></span><h2>Contact Informations</h2></div>
            <ul>
                <li><span>Location:</span> <%= my_location %></li>
                <li><span>Job:</span> <%= my_job_title %></li>
                <li><span>E-mail:</span> <%= my_email %></li>
                <li>
                    <div class="social-icons top_15"> 
                        <a class="fb" href="<%= facebook_url %>" target="_blank">
                            <i class="fa fa-facebook" aria-hidden="true"></i>
                        </a> 
                        <a class="li" href="<%= linkedin_url %>" target="_blank">
                            <i class="fa fa-linkedin" aria-hidden="true"></i>
                        </a> 
                    </div>
                </li>
            </ul>
        </section>
        <!-- Contact Map -->
        <section class="contact-map col-md-12 top_15 bottom_15">
            <div class="section-title bottom_30"><span></span><h2>Contact Map.</h2></div>
            <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d99366.31324092453!2d-94.89107507034397!3d38.89660352943801!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x87c097a5101f4f41%3A0xc18238569d7e7db0!2sOlathe%2C%20KS!5e0!3m2!1sen!2sus!4v1571800519274!5m2!1sen!2sus" height="350" frameborder="0" style="border:0;" allowfullscreen=""></iframe>
        </section>
    </div>
</div>